version: '3.8'
services:
  php:
    container_name: php-${CONTAINER_NAME}
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        APK_PACKAGES: ${APK_PACKAGES}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - ./sites:/var/www/html
      - ./apache/default.conf:/etc/apache2/conf.d/default.conf
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - php

networks:
  php:
    driver: bridge